// result generated by the user (all false at the start)
let sectionUser = [
    [false, false, false, false, false, false],
    [false, false, false, false, false, false],
    [false, false, false, false, false, false],
    [false, false, false, false, false, false]
];

const sections = [{
        name: "Playground",
        tempo: 120,
    },
]