const soundsToPlay = [false, true, false, false, false, true];

// result generated by the user (all false at the start)
let partitionUser = [
    [false, false, false, false, false, false],
    [false, false, false, false, false, false],
    [false, false, false, false, false, false],
    [false, false, false, false, false, false]
];


// game rounds - easy more
const easyPartitions = [{
        name: "Just The Kick",
        tempo: 120,
        difficulty: 1,
        time: 45,
        notes: [
            [true, false, false, false, false, false],
            [false, false, false, false, false, false],
            [true, false, false, false, false, false],
            [false, false, false, false, false, false]
        ]
    },
    {
        name: "Drop The Bass",
        tempo: 120,
        difficulty: 2,
        time: 45,
        notes: [
            [false, false, false, false, false, true],
            [false, false, false, false, false, true],
            [false, false, false, true, false, false],
            [false, true, false, false, false, false]
        ]
    },
    {
        name: 'We will Rock You!',
        tempo: 60,
        time: 45,
        difficulty: 4,
        notes: [
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
            [false, true, false, false, true, false],
            [false, false, false, false, false, false]
        ]
    },
    {
        name: 'Getting Funky',
        tempo: 150,
        time: 60,
        difficulty: 4,
        notes: [
            [true, false, true, false, false, true],
            [false, false, true, false, false, false],
            [true, false, true, false, true, false],
            [false, false, true, false, true, true]
        ]
    }

]